### ISSUE TITLE
Allow deleting leaf categories in order to include their parents

### ISSUE THREAD

**Issue by edufonseca** [xavierfav/Freesound-data-set#2]
Often we want to fous on the leaf categories because they are the most meaningful. But it is not always true. There are a numberof leaf categories that can be very specific. Examples

- Pizzicato is children of Violin, fiddle
- Alto or Soprano Saxophone  are children of Saxo

Sometimes, these categories are accepted, driven by the number and quality of samples available. But it can be advategoues to remove them manually in favor of the most representative parent.

This can be added in pre-processing, as another strong filter, after the filter of leaves categories. Hence the parent will be detected as candidate and samples from their children will be aggregated to it.

**Comment by jordipons** [comment]
I agree, and I also wanted to remark that it posibly makes more sense to consider using Saxophone (instead of Soprano Saxophone) for creating a possible dataset. However, having the class Pizzicato (instead of Violin, fiddle) makes sense if most sounds we have are Pizzicato - but, agree, it is worth checking the class Violin, fiddle to see if many variate examples (not only Pizzicato) are there.
